version: 1
services:
  - type: web
    name: ocr-app
    env: python
    buildCommand: |
      ./setup.sh
      pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port 8080
